# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Concert Memories                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Revive and share your concert experiences with friends.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Eros Bonanni                                
your_link                                 : https://concertmemoriesapp.com                    
your_city                                 : Mar del Plata                                
email_address                             : erosbonanni@icloud.com
facebook_username                         :                                           
instagram_username                        : imjusterxs
twitter_username                          : ErosBonanni
github_username                           : ErosBonanni
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Countdown
    description                           : For those who can't wait, how many days to go to the concert?
    fontawesome_icon_name                 : calendar-alt
    
  - title                                 : Memories
    description                           : You can add photos, videos and notes, of your concert experience.
    fontawesome_icon_name                 : images

  - title                                 : Social
    description                           : See how other people also freaks out just like you!
    fontawesome_icon_name                 : user-friends

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#FFFFFF"
topbar_transparency                       : 0
topbar_title_color                        : "#303030"

cover_image                               : #assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "fcfcfc"

link_color                                : "#1d63ea"

app_title_color                           : "#303030"
app_price_color                           : "#303030"
app_description_color                     : "#303030"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#303030"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#303030"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
